server:
   port: ${PORT:8000}
   servlet: 
      context-path: /springboot2
      
# H2
spring: 
      h2:
        console: 
              enabled: true
              path: /h2
              
      datasource: 
               url: ${h2-url:jdbc:h2:file:~/spring-boot-h2-db;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE}
               username: sa
               password: 
               driverClassName: org.h2.Driver
      jpa: 
        hibernate:
                ddlAuto: update           
      
      kafka: 
        bootstrap-servers: velomobile-01.srvs.cloudkafka.com:9094,velomobile-02.srvs.cloudkafka.com:9094,velomobile-03.srvs.cloudkafka.com:9094
        properties: 
                 security: 
                        protocol: SASL_SSL
                 sasl: 
                    mechanism: SCRAM-SHA-256  
                               
                  
        consumer: 
          group-id: springboot2
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.apache.kafka.common.serialization.StringSerializer
          
     
          